export const constants = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_SELECTED: "GET_SELECTED",
  SHOW_SELECTED: "SHOW_SELECTED",
  HIDE_SELECTED: "HIDE_SELECTED",
  GET_CART_PRODUCT: "GET_CART_PRODUCT",
  REMOVE_CART_PRODUCT:'REMOVE_CART_PRODUCT',
  IS_CART_ADDED:'IS_CART_ADDED',
  SHOW_CART:'SHOW_CART',
  GET_CART_FIREBASE:'GET_CART_FIREBASE'
};
